### ISSUE TITLE
[PHP-API] Using $this when not in object context

### ISSUE THREAD

**Issue by Zeryther** [MC-API/Issues#13]
I just got this error:
```php
Fatal error: Using $this when not in object context in C:\xampp\htdocs\antihivespieler\assets\incl\uuid_api.class.php on line 36
```

My code:
```php
<?php print uuid_api::uuidToName($row["author_uuid"]); ?>
```

The used UUID:
```php
73b417dc-d1e6-45d8-af06-895eeb5222a5
```

**Comment by njb-said** [comment]
@Zeryther 
Sorry for the late response, was on vacation.

Anyway, the reason you are getting this error is because you haven't made an instance of the uuid_api class, however I will shortly be editing it to be static. If you can wait for me to do that then that's great, if not I suggest (for now at least) you create a temporary instance of the class.

```php
$uuid_api = new uuid_api();
```

**Comment by Zeryther** [comment]
Thanks for the help! You don't have to hurry ^^ It was just a little thing I wanted to improve on my website ^^
