### ISSUE TITLE
EU server not resolving names

### ISSUE THREAD

**Issue by Cloudhunter** [MC-API/Issues#39]
As per the title! It appears the EU API is having difficulty resolving names direct from Mojang.

Example, on the EU API: http://prntscr.com/b2vhrc

Nicks in the database/cache appear to work: http://prntscr.com/b2vi9g

Same query in the US API: http://prntscr.com/b2viok (says cache this time - but the previous time it got it direct from Mojang).

Isn't just affecting the interface - affecting the API too.

Broken: https://eu.mc-api.net/v3/uuid/Cloudhunter
Working: https://us.mc-api.net/v3/uuid/Cloudhunter

Let me know if you need anything!

**Comment by njb-said** [comment]
Apologises about these, we have been having a few capacity issues for the last week or so.
A few users are abusing the API causing it to have rate limiting problems from Mojang, I have been adding capacity as much as I can (quite costly to do)
I have also been blocking users who are abusing the API, this has helped lower some but not all of the errors.
The reason the US servers are responding to queries better than EU is because the abusive users are using the EU servers. If you wish to use US please go ahead.

I am debating adding more capacity again, but as it is expensive and comes out of my pocket I am against it :unamused: 
For now please bear with us, I am investigating other solutions as well as proactively blacklisting abusive IP addresses.
You can follow us on twitter if you want to keep up-to-date: :information_source: 
[twitter.com/mc_api](https://twitter.com/mc_api)

**Comment by ImNatho** [comment]
Ref #40
