### ISSUE TITLE
MC API not working in general

### ISSUE THREAD

**Issue by Reichmann-M** [MC-API/Issues#60]
In my opinion the api service is not working at all at the moment. I've been using it for a few months and today suddenly I got no response from my bot anymore. I dived deep in my code for possible bugs bot found none. I also tested it with three different servers (all with different IP's, just to exclude possible IP-bans but this also shouldn't be the problem because I always have a 60 second timeout after each request). 

So I checked the whole accessibility of the api and it turned out to be not available at all. I tried different checks and all told me the same:  
https://downforeveryoneorjustme.com/eu.mc-api.net
https://browserleaks.com/ip/eu.mc-api.net

I also asked my friend to go on https://eu.mc-api.net/ and it didn't work for him.

**Comment by njb-said** [comment]
Hi,

I had a look when you originally opened this issue and have been monitoring the service uptime closely since, and there doesn't appear to be any issues with the api that I can see. Are you still having this issue?

Sites such as downforeveryoneorjustme.com generally ping the website from their service and see if they get a response which can be a bit misleading, as it doesn't always show an issue if there is one - for example if a behind the scenes service supporting the api is running slowly or is down it may not be evident.

If you have the issue again could you post the HTTP response you get (if any) such as the response headers and status code as this will help me diagnose the issue 🙂 

Alternatively, feel free to join the Discord server where I might be able to help more: https://discord.gg/pwBh52S

**Comment by Reichmann-M** [comment]
Hey,

sorry for this late answer but today I tried reaching the service from my external server and it seems working again. So probably there just had been some connection issues the other day. It looks quite promising again.

Nevertheless thank you for your help and support in your answer.

Imma close this topic now.
